In [8]:
import numpy as np


In [9]:
array1=np.random.randint(25,size=(5,5))
print(array1)

[[ 7 24  9 20  5]
 [15  1 14 14 19]
 [ 8 13 22 10 19]
 [21 20 11  4 21]
 [ 2  6 15 16  0]]


In [10]:
print("Mean",array1.mean())
print("Standard Deviation",array1.std())
print("Variance",array1.var())

Mean 12.64
Standard Deviation 7.024983985746871
Variance 49.3504


In [11]:
B=[56,48,22,41,78,91,24,46,8,33]
array2=np.array(B)
print(array2)

[56 48 22 41 78 91 24 46  8 33]


In [12]:
print("SortedIndices",np.argsort(array2))

SortedIndices [8 2 6 9 3 7 1 0 4 5]


In [27]:
m=int(input("Enter the row size : "))
n=int(input("Enter the column size : "))
array3=np.random.randint(m*n,size=(m,n))
print(array3)


Enter the row size : 3
Enter the column size : 4
[[ 6  7  3  4]
 [10  2  0  5]
 [ 4  1  6  0]]


In [29]:
print("shape",array3.shape)
print("Type",type(array3))
array5=array3.reshape(4,3)


shape (3, 4)
Type <class 'numpy.ndarray'>


In [30]:
array5.shape

(4, 3)

In [7]:
c=[3,0,0,1,4,np.nan,5,np.nan,6,0,5]
array4=np.array(c)

In [41]:
print(np.where(array4==0)[0])
print(np.where(array4!=0)[0])
array6=(np.isnan(array4))
array6
print(np.where(array6==True)[0])

[1 2 9]
[ 0  3  4  5  6  7  8 10]
[5 7]
